#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# scripts/lib/nginx-helpers.sh — Nginx vhost management for staging instances
# Requires: common.sh sourced first (provides INSTALL_DIR, DOMAIN_STAGING, etc.)
# ─────────────────────────────────────────────────────────────────────────────

NGINX_CONTAINER="${NGINX_CONTAINER:-nginx_odoo}"
NGINX_STAGING_CONF_DIR="${STAGING_DIR}/nginx"

# ── Generate nginx vhost for a staging instance ──────────────────────────────
# Usage: generate_nginx_vhost <name> <port>
# Creates: staging/nginx/stg-{name}.conf
generate_nginx_vhost() {
  local name="$1"
  local port="$2"
  local subdomain="${name}.${DOMAIN_STAGING}"
  local conf_path="${NGINX_STAGING_CONF_DIR}/stg-${name}.conf"

  mkdir -p "$NGINX_STAGING_CONF_DIR"

  cat > "$conf_path" << NGINXVHOST
# Auto-generated by staging-manager.sh for stg-${name}
# Do not edit manually — regenerate by running staging-manager.sh

server {
    listen 80;
    server_name ${subdomain};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name ${subdomain};

    ssl_certificate     /etc/letsencrypt/live/${subdomain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${subdomain}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    access_log /var/log/nginx/stg-${name}-access.log;
    error_log  /var/log/nginx/stg-${name}-error.log;

    client_max_body_size 200M;
    proxy_read_timeout 720s;
    proxy_connect_timeout 720s;
    proxy_send_timeout 720s;

    location / {
        proxy_pass http://host.docker.internal:${port};
        proxy_set_header Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_redirect off;
    }

    location /websocket {
        proxy_pass http://host.docker.internal:${port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400;
    }

    location ~* /web/static/ {
        proxy_pass http://host.docker.internal:${port};
        proxy_cache_valid 200 60m;
        proxy_buffering on;
        expires 24h;
    }
}
NGINXVHOST

  log_info "Generated nginx vhost: $conf_path (subdomain: $subdomain)"
}

# ── Reload nginx inside container ─────────────────────────────────────────────
reload_nginx() {
  if ! is_container_running "$NGINX_CONTAINER"; then
    log_warn "Nginx container '$NGINX_CONTAINER' is not running — skipping reload"
    return 0
  fi
  log_info "Reloading Nginx..."
  if docker exec "$NGINX_CONTAINER" nginx -t 2>&1; then
    docker exec "$NGINX_CONTAINER" nginx -s reload
    log_info "Nginx reloaded successfully"
  else
    log_error "Nginx config test failed — reload aborted"
    return 1
  fi
}

# ── Request SSL certificate for a subdomain ───────────────────────────────────
# Usage: request_ssl_cert <domain>
request_ssl_cert() {
  local domain="$1"

  if [ -z "$SSL_EMAIL" ]; then
    log_error "SSL_EMAIL not set in .deploy-config — cannot request certificate"
    return 1
  fi

  log_info "Requesting SSL certificate for $domain..."

  # Stop nginx temporarily to free port 80 for standalone challenge
  if is_container_running "$NGINX_CONTAINER"; then
    docker stop "$NGINX_CONTAINER"
  fi

  local cert_obtained=false
  if certbot certonly --standalone \
    -d "$domain" \
    --email "$SSL_EMAIL" \
    --agree-tos \
    --no-eff-email \
    --non-interactive 2>&1; then
    cert_obtained=true
    log_success "SSL certificate obtained for $domain"
  else
    log_warn "Could not obtain SSL cert for $domain — using self-signed fallback"
    mkdir -p "/etc/letsencrypt/live/$domain"
    openssl req -x509 -nodes -days 30 \
      -newkey rsa:2048 \
      -keyout "/etc/letsencrypt/live/$domain/privkey.pem" \
      -out "/etc/letsencrypt/live/$domain/fullchain.pem" \
      -subj "/CN=$domain" 2>/dev/null
    log_warn "Self-signed cert created for $domain (browser will warn 'Not Secure')"
  fi

  # Restart nginx
  docker start "$NGINX_CONTAINER"
  sleep 2

  if [ "$cert_obtained" = "true" ]; then
    reload_nginx
  fi
}

# ── Remove nginx vhost for an instance ───────────────────────────────────────
remove_nginx_vhost() {
  local name="$1"
  local conf_path="${NGINX_STAGING_CONF_DIR}/stg-${name}.conf"

  if [ -f "$conf_path" ]; then
    rm -f "$conf_path"
    log_info "Removed nginx vhost: $conf_path"
    reload_nginx || true
  else
    log_info "No nginx vhost found for stg-${name}, skipping"
  fi
}

# ── Check if vhost exists ─────────────────────────────────────────────────────
nginx_vhost_exists() {
  local name="$1"
  [ -f "${NGINX_STAGING_CONF_DIR}/stg-${name}.conf" ]
}
